- name: Obfuscate & Domain Lock
        run: |
          for f in js/*.js; do
            if [[ ! $f == *.min.js ]]; then
              # Thêm --ignore-require true để tránh lỗi với các thư viện bên ngoài
              javascript-obfuscator "$f" \
                --output "${f%.js}.min.js" \
                --compact true \
                --domain-lock 'vutruong.vn', 'cdn.vutruong.vn', 'localhost' \
                --domain-lock-redirect-url 'https://vutruong.vn' \
                --self-defending false \
                --string-array true
            fi
          done
